### ISSUE TITLE
PHP Deprecated:  Required parameter $contentType follows optional parameter $filename

### ISSUE THREAD

**Issue by bfoosness** [mikehaertl/php-tmpfile#21]
This line results in a deprecation error in PHP 8:

**PHP Deprecated:  Required parameter $contentType follows optional parameter $filename in /site/vendor/mikehaertl/php-tmpfile/src/File.php on line 73**

https://github.com/mikehaertl/php-tmpfile/blob/20a1879033d6b044cfba5dfcf55cbb418249d0ec/src/File.php#L73

I'm happy to create a PR if you have a preferred solution. Changing the parameter order or requiring the first parameter would be a BC break. Alternatively, a default value of null could be added to `$contentType` (turning it into an optional parameter) and then an exception thrown if it remains null.

**Comment by mikehaertl** [comment]
Thanks, will have a look. Maybe we should use `mime_content_type()` if no `$contentType` is passed and let it default to `application/octet-stream` if that function also fails. What do you think?

I first thought about making the `Content-Type` header optional but I think this will break the download in some browsers so it should always be set.

**Comment by bfoosness** [comment]
Yeah, if you think that's a reasonable default, that could be a good solution. There _shouldn't_ be any calls to this method without a content type now, so any immediate consequences to this default value should be minimal to none, making it a safe change.

**Comment by bfoosness** [comment]
I've created an initial attempt at a fix if you'd like to discuss it. Unfortunately there are no tests covering the send method.

**Comment by mikehaertl** [comment]
@bfoosness Just released 1.1.7 including this fix. Thanks for your help.

**Comment by bfoosness** [comment]
Thanks so much!
