### ISSUE TITLE
File permission issue

### ISSUE THREAD

**Issue by gjt211** [mikehaertl/php-tmpfile#5]
Hi, I have just quickly tried your code and it works using $file->send (I had to add in the content type), however when I try to use $file->saveAs I get the following error.
```
Warning: copy(test.txt): failed to open stream: Permission denied in <filepath hidden>/includes/File.php on line 98
```
Can you please advise?

**Comment by mikehaertl** [comment]
Well, the error says it all, doesn't it? You have no permission to write the file to the destination. Nothing to fix on our side.

**Comment by gjt211** [comment]
Thanks for your prompt reply.

I understand what the error message means, so why does the send method work whereas the saveAs doesn't?

A little bit of friendly advice would have been appreciated rather than the blunt reply you provided. Great work being part of the open source community and making available excellent code and instantly closing the issue without even offering a fix.

**Comment by mikehaertl** [comment]
Well, `send()` does not save the file, whereas `saveAs()` does. There is nothing to fix here and I really get too many "bug reports" that are not bugs at all but a problem in the developers code. Please understand that this is extremely frustrating for me and I don't have the time to answer all these questions and help find the problems in other peoples code. I really already try to do my best to keep this library free of issues.

**Comment by gjt211** [comment]
Thanks again.
Sorry for my fast and also blunt reply before.
Your last reply is much more appreciated, so really a big thank you.

I am also very time poor and would hope that when I do try to use a library or code that someone such as yourself has generously made available that it works, or at least might provide some slightly more than basic instructions on its use and implementation.
I know writing documentation is a pain and time consuming. I also guess you wrote this for yourself and decided to kindly share it with the world.

I was not aware that the saveAs option wrote to the filesystem, but now I am. With that in mind, I completely understand that the file permission error is my problem, not yours.

Keep up the great work and thanks for your reply.
